name: Build for iPad

on:
  push:
    branches: [main]
  workflow_dispatch:
  schedule:
    - cron: "0 0 * * 0"

jobs:
  build:
    runs-on: macos-15
    timeout-minutes: 30

    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Setup Xcode
        uses: maxim-lobanov/setup-xcode@v1
        with:
          xcode-version: latest-stable

      - name: Install fastlane
        run: |
          gem install fastlane -N --no-doc

      - name: Create keychain
        run: |
          security create-keychain -p "" build.keychain
          security default-keychain -s build.keychain
          security unlock-keychain -p "" build.keychain
          security set-keychain-settings -t 3600 -u build.keychain

      - name: Build IPA
        timeout-minutes: 20
        run: fastlane build_and_deploy
        env:
          FASTLANE_USER: ${{ secrets.APPLE_ID }}
          FASTLANE_APPLE_APPLICATION_SPECIFIC_PASSWORD: ${{ secrets.APPLE_APP_SPECIFIC_PASSWORD }}
          APPLE_ID: ${{ secrets.APPLE_ID }}
          DEVICE_UDID: ${{ secrets.DEVICE_UDID }}
          TEAM_ID: ${{ secrets.TEAM_ID }}
          APP_BUNDLE_ID: "com.rearviewpip.zyl"

      - name: Upload IPA
        uses: actions/upload-artifact@v4
        with:
          name: RearViewPiP
          path: build/RearViewPiP.ipa
          retention-days: 7
